In [36]:
import numpy as np
def coinChange(S, sum):

    dp = [[0 for _ in range(sum + 1)] for _ in range(len(S)+1)]

    for i in range(1, len(S) + 1):
        for j in range(1, sum + 1):
            dp[i][j] = float('inf')

            if j < S[i-1]:
                dp[i][j] = dp[i - 1][j]
            elif i==j or i==1:
                dp[i][j] = 1 + dp[i][j - S[i-1]]
            else:
                dp[i][j] = min(dp[i - 1][j], 1 + dp[i][j - S[i-1]])


    return dp

def coins_used(S, dp):
    i = dp.shape[0] - 1
    j = dp.shape[1] - 1
    solution_set = []
    while j > 0:
        if dp[i][j] == dp[i - 1][j]:
            i -= 1
        else:
            solution_set.append(S[i-1])
            j -= S[i - 1]

    return solution_set

S = [1, 4, 6]
sum = 8
dp = coinChange(S, sum)
dp = np.array(dp)
print(f'Number of coins required to make sum {sum} from denominations {S} = {dp[-1][-1]} \n')

print(f'Table of coins: \n{dp} \n')

solution_set = coins_used(S, dp)
print(f'Solution set: {solution_set}')

Number of coins required to make sum 8 from denominations [1, 4, 6] = 2 

Table of coins: 
[[0 0 0 0 0 0 0 0 0]
 [0 1 2 3 4 5 6 7 8]
 [0 1 2 3 1 2 3 4 2]
 [0 1 2 3 1 2 1 2 2]] 

Solution set: [4, 4]
